spring:
  application:
    name: eureka-client
server:
  port: 8001
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8000/eureka,http://localhost:9000/eureka

logging:
  path: ./target/log
  config: classpath:logback-boot.xml
  file: ${spring.application.name}.log




